language: common-lisp
sudo: false

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_BRANCH=master
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - COVERAGE_EXCLUDE=t
  matrix:
    - LISP=sbcl-bin COVERALLS=true

install:
  # Roswell & coveralls
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - git clone https://github.com/fukamachi/cl-coveralls ~/lisp/cl-coveralls
  # Clone cl-libyaml
  - git clone https://github.com/eudoxia0/cl-libyaml.git ~/lisp/cl-libyaml

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

before_script:
  - ros --version
  - ros config

script:
  - ros -e '(ql:quickload (list :fiveam :cl-coveralls :cl-yaml-test))'
        -e '(setf fiveam:*debug-on-error* t
                  fiveam:*debug-on-failure* t)'
        -e '(setf *debugger-hook*
                  (lambda (c h)
                    (declare (ignore c h))
                    (uiop:quit -1)))'
        -e '(coveralls:with-coveralls (:exclude (list "t" "src/error.lisp"))
              (cl-yaml-test:run-tests))'

notifications:
  email:
    - eudoxiahp@gmail.com
